spring:
  application:
    name: ingestion-api
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbit:
    exchange: crm.exchange
    routing-key: crm.campaign.created
    queue: crm.campaign.queue

logging:
  level:
    org.springframework.amqp: DEBUG

security:
  api-key: secret-key


server:
  port: 8080