import { useState, useMemo } from 'react';

import CampaignContent from './CampaignContent';
import AttendeeContent from './AttendeeContent';

import { toRequiredText, toNullable, validateCampaignForm } from '../helpers/HelperFunctions';
import { syncCampaigns } from '../api/crmApi';

import Button from './Button';

function FormCampaign() {

    /* CREATING FUNCTIONS */

    // Create the initial form state, including one empty attendee row (object + array of objects)
    const createInitialForm = () => ({
        campaignId: '',
        subCampaignId: '',
        attendees: [createEmptyAttendee()],
    });

    // Creates a new empty attendee object
    const createEmptyAttendee = () => ({
        rowId: crypto.randomUUID(),
        cn: '',
        firstName: '',
        lastName: '',
        birthDate: '',
        partnerId: '',
        isCompanion: false,
        qrCode: '',
    });

    /* USE STATE + SETTING FUNCTIONS */

    /* Stores the entire form state. The initial value is generated by createInitialForm().
    setFormData is used to update the form when an input value changes. */
    const [formData, setFormData] = useState(createInitialForm);

    // Tracks whether the form is currently being submitted
    const [isSubmitting, setIsSubmitting] = useState(false);

    // Stores the feedback message shown to the user
    const [feedback, setFeedback] = useState({
        type: '',
        message: '',
    });

    // Frontend form validation errors state
    const [validationErrors, setValidationErrors] = useState({
        campaignId: '',
        attendees: {},
    });
        

    /* HANDLING FUNCTIONS */

    // Handles changes for the campaign fields and updates formData (with setFormData function)
    const handleChangeCampaign = (event) => {
        const { name, value } = event.target;

        setFormData((current) => ({
            ...current,
            [name]: value,
        }));
    };

    /* Handles changes for attendee fields (with setFormData function)
    - Finds the attendee by rowId
    - Updates only the selected field */
    const handleChangeAttendee = (rowId, field, value) => {
        setFormData((current) => ({
            ...current,
            attendees: current.attendees.map((attendee) =>
                attendee.rowId === rowId ? { ...attendee, [field]: value } : attendee
            ),
        }));
    };

    // Adds a new empty attendee to the form
    const addAttendee = () => {
        setFormData((form) => ({
            ...form,
            attendees: [...form.attendees, createEmptyAttendee()],
        }));
    };

    // Clears the form and removes the current feedback message
    const clearForm = () => {
        setFormData(createInitialForm());
        setFeedback({
            type: '',
            message: '',
        });
        setValidationErrors({ campaignId: '', attendees: {} });
    };
    
    /* FINAL FUNCTIONS */
    
    /* Builds the payload to send to the backend.
    It returns a new object without mutating the original form state. */
    const buildCampaignPayload = (form) => ({
        campaignId: toRequiredText(form.campaignId),
        subCampaignId: toNullable(form.subCampaignId),
        attendees: form.attendees.map(({ rowId, ...attendee }) => ({
            ...attendee,
            cn: toNullable(attendee.cn),
            firstName: toRequiredText(attendee.firstName),
            lastName: toRequiredText(attendee.lastName),
            birthDate: toNullable(attendee.birthDate),
            partnerId: toRequiredText(attendee.partnerId),
            qrCode: toRequiredText(attendee.qrCode),
        })),
    });


    // Handles form submission.
    const handleSubmit = async (event) => {

        // Prevents the default browser form submission
        event.preventDefault();

        // RUN VALIDATION
        const validation = validateCampaignForm(formData);

        if (!validation.isValid) {
            setValidationErrors(validation.errors); 
            setFeedback({
                type: 'error',
                message: 'Validation failed. Please check the fields.',
            });
            return;
        }

        // Reset previous errors if validation passes
        setValidationErrors({ campaignId: '', attendees: {} });

        // Sets the loading state and shows a feedback message
        setIsSubmitting(true);

        setFeedback({
            type: 'loading',
            message: 'Sending request to Producer...',
        });

        try {
            // Builds the payload from the current form data
            const campaignPayload = buildCampaignPayload(formData);

            // Sends the request to the backend
            await syncCampaigns(campaignPayload);

            // Updates the feedback message based on the response
            setFeedback({
                type: 'success',
                message: 'Request accepted (202). Campaign queued successfully.',
            });

            // Resets the form after a successful submission
            setFormData(createInitialForm());

        } catch (error) {
            // All the feedback error messages are based on the custom error code set in the CrmAPI.js file
            switch (error.code) {
                case 'BAD_REQUEST':
                    setFeedback({ type: 'error', message: 'Bad request (400). Check required fields.' });
                    break;
                case 'UNAUTHORIZED':
                    setFeedback({ type: 'error', message: 'Unauthorized (401). Check X-API-KEY.' });
                    break;
                case 'NETWORK_ERROR':
                    setFeedback({ type: 'error', message: 'Network error or timeout.' });
                    break;
                default:
                    setFeedback({ type: 'error', message: 'Unexpected error while sending the request.' });
            }
        } finally {
            setIsSubmitting(false);
        }
    };

    // Payload preview memo
    const previewPayload = useMemo(() => {
        return [buildCampaignPayload(formData)];
    }, [formData]);

  
    return (
        <section>
            <form onSubmit={handleSubmit}>
                <h2>Campaign Submission Form</h2>
                <hr />
                <h3>Create a new campaign</h3>

                <CampaignContent formData={formData} onChange={handleChangeCampaign}  errors={validationErrors}
                isSubmitting={isSubmitting}  />     
                    
                <h3>Add attendees</h3>

                <fieldset className="new_attendee">
                    
                    {formData.attendees.map((attendee) => (
                        <AttendeeContent key={attendee.rowId} attendee={attendee} 
                        onFieldChange={handleChangeAttendee}  isSubmitting={isSubmitting}   
                        errors={validationErrors.attendees[attendee.rowId]} />   
                    ))}
                </fieldset>
            
                <div className="action">
                    <Button text="+ Add Attendee" variant="primary" onClick={addAttendee} disabled={isSubmitting}/>
                </div>

                <hr />

                {feedback.message && (
                    <div className={`form-feedback ${feedback.type}`}>
                        {feedback.message}
                    </div>
                )}

                <div className="action">
                    <Button type="submit" text={isSubmitting ? 'Sending...' : 'Submit Campaign'} variant="primary" disabled={isSubmitting}/>
                    <Button type="button" text="Clear Form" variant="danger" onClick={clearForm} disabled={isSubmitting}/>
                </div>
            </form>
        </section>
    );
}

export default FormCampaign;