import Toggle from './Toggle';
import Button from './Button';

import { useState } from 'react';
import { syncCampaigns } from '../api/CrmAPI';

function FormCampaign() {
    
    
    // Create the initial form state, including one empty attendee row (object + array of objects)
    const createInitialForm = () => ({
        campaignId: '',
        subCampaignId: '',
        attendees: [createEmptyAttendee()],
    });

    // Creates a new empty attendee object
    const createEmptyAttendee = () => ({
        rowId: crypto.randomUUID(), 
        cn: '',
        firstName: '',
        lastName: '',
        birthDate: '',
        partnerId: '',
        isCompanion: false,
        qrCode: '',
    });

    /* Stores the entire form state. The initial value is generated by createInitialForm().
    setFormData is used to update the form when an input value changes. */
    const [formData, setFormData] = useState(createInitialForm);
    
    // Tracks whether the form is currently being submitted
    const [isSubmitting, setIsSubmitting] = useState(false);
    
    // Stores the feedback message shown to the user
    const [feedback, setFeedback] = useState({
        type: '',
        message: '',
    });
    
    // Handles changes for the campaign fields and updates formData (with setFormData function)
    const handleChangeCampaign = (event) => {
        
        const { name, value } = event.target;

        setFormData((current) => ({
        ...current,
        [name]: value,
        }));
    };

    /* Handles changes for attendee fields (with setFormData function)
    - Finds the attendee by rowId
    - Updates only the selected field */
    const handleChangeAttendee = (rowId, field, value) => {
        setFormData((current) => ({
        ...current,
        attendees: current.attendees.map((attendee) =>
            attendee.rowId === rowId ? { ...attendee, [field]: value } : attendee  
        ),
        }));
    };

    // Adds a new empty attendee to the form
    const addAttendee = () => {
        setFormData((form) => ({
        ...form,
        attendees: [...form.attendees, createEmptyAttendee()],
    }));
    };

    // Removes an attendee by rowId; if only one attendee remains, resets it to an empty row
    const removeAttendee = (rowId) => {
        setFormData((current) => {
        if (current.attendees.length === 1) {
            return {
            ...current,
            attendees: [createEmptyAttendee()],
            };
        }

        return {
            ...current,
            attendees: current.attendees.filter((attendee) => attendee.rowId !== rowId), 
        };
        });
    };

    // Trim spaces from specific values
    const toRequiredText = (value) => value.trim();

    /* Builds the payload to send to the backend.
    It returns a new object without mutating the original form state. */
    const buildCampaignPayload = (form) => ({
        campaignId: toRequiredText(form.campaignId),
        subCampaignId: toNullable(form.subCampaignId),
        attendees: form.attendees.map(({ rowId, ...attendee }) => ({
            ...attendee,
            cn: toNullable(attendee.cn),
            firstName: toRequiredText(attendee.firstName),
            lastName: toRequiredText(attendee.lastName),
            birthDate: toNullable(attendee.birthDate),
            partnerId: toRequiredText(attendee.partnerId),
            qrCode: toRequiredText(attendee.qrCode),
        })),
    });

    // Handles form submission.
    const handleSubmit = async (event) => {

        // Prevents the default browser form submission
        event.preventDefault();

        // Sets the loading state and shows a feedback message
        setIsSubmitting(true);
        
        setFeedback({
            type: 'loading',
            message: 'Sending request to Producer...',
        });

        try {

            // Builds the payload from the current form data
            const campaignPayload = buildCampaignPayload(formData);

            // Sends the request to the backend
            await syncCampaigns(campaignPayload);

            // Updates the feedback message based on the response
            setFeedback({
                type: 'success',
                message: 'Request accepted (202). Campaign queued successfully.',
            });

            // Resets the form after a successful submission
            setFormData(createInitialForm());
        
        } catch (error) {

            // All the feedback error messages
            if (error.status === 400) {
                setFeedback({
                    type: 'error',
                    message: 'Bad request (400). Check required fields and payload format.',
                });
            } else if (error.status === 401) {
                setFeedback({
                    type: 'error',
                    message: 'Unauthorized (401). Check X-API-KEY.',
                });
            } else {
                setFeedback({
                    type: 'error',
                    message: 'Unexpected error while sending the request.',
                });
            }
        
        } finally {
            setIsSubmitting(false);
        }
    };
        

    return (

        <section>

            <form onSubmit={handleSubmit}> 
                
                <h2>Campaign Submission Form</h2>
                <hr></hr>
                <h3>Create a new campaign</h3>
                
                <fieldset className="new_campaign">

                    <label htmlFor="campaign_name">Campaign name</label>
                    <input type="text" id="campaign_name" placeholder="Es. BUCCAMP0001" name="campaignName" value={formData.campaignName} onChange={handleChangeCampaign}></input>

                    <label htmlFor="campaign_id">Sub-campaign ID</label>
                    <input type="text" id="campaign_id" placeholder="Es. SC-0091" name="subCampaignId" value={formData.campaignId} onChange={handleChangeCampaign}></input>
             
                </fieldset>

                <h3>Add attendees</h3>

                <fieldset className="new_attendee">

                    {formData.attendees.map((attendee) => (

                        <div>

                            <div className="fields_column">
                            
                                <div className="fields">
                                    <label htmlFor="first_name">First name</label>
                                    <input type="text" id="first_name" placeholder="Es. Mario" value={attendee.firstName}
                                        onChange={(event) => handleChangeAttendee(attendee.rowId, 'firstName', event.target.value)}/>
                                </div>

                                <div className="fields">
                                    <label htmlFor="partner_id">Partner Id</label>
                                    <input type="text" id="partner_id" placeholder="Es. Maria Rossi" value={attendee.partnerId}
                                        onChange={(event) => handleChangeAttendee(attendee.rowId, 'partnerId', event.target.value)}/>
                                </div>
                                
                                <div className="fields">
                                    <label htmlFor="cn_code">CN Code</label>
                                    <input type="text" id="cn_code" placeholder="Es. 1234" value={attendee.cn} 
                                        onChange={(event) => handleChangeAttendee(attendee.rowId, 'cn', event.target.value)}/>
                                    
                                </div>
                            </div>


                            <div className="fields_column">

                                <div className="fields">
                                    <label htmlFor="last_name">Last name</label>
                                    <input type="text" id="last_name" placeholder="Es. Rossi" value={attendee.lastName}
                                        onChange={(event) => handleAttendeeChange(attendee.rowId, 'lastName', event.target.value)}/> 
                                </div> 
                                
                                <Toggle />
                                
                                <div className="fields">
                                    <label htmlFor="qr_code">Qr Code</label>
                                    <input id="qr_code" type="text" placeholder="Es. xxxxxx" value={attendee.qrCode} 
                                        onChange={(event) => handleChangeAttendee(attendee.rowId, 'qrCode', event.target.value)}/>
                                </div>

                            </div>


                            <div className="fields_column">
                                
                                <div className="fields">
                                    <label htmlFor="birth_date">Birth date</label>
                                    <input type="date" id="birth_date" value={attendee.birthDate}
                                        onChange={(event) => handleChangeAttendee(attendee.rowId, 'birthDate', event.target.value)} />
                                </div>

                            </div>
                        
                            <Button text="+ Add Attendee" variant="primary" onClick={addAttendee} />  
                            <Button text="Delete Attendee" variant="danger" onClick={removeAttendee} />

                        </div>
                    
                    ))}

                </fieldset>
                       
            
                <hr></hr> 
             
                <div className="action">

                    <Button text="Submit Campaign" variant="primary" onClick={handleSubmit} />
                    <Button text="Clear Form" variant="danger" onClick={clearForm} />
                
                </div>
                
            </form>
            
        </section>
        
    )
}


export default FormCampaign