spring:
  application:
    name: event-worker

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/ess_data
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

  RabbitMQ:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-retries: 3
          initial-interval: 1000
  mail:
    host: localhost
    port: 1025
    protocol: smtp
    username: ""
    password: ""
    properties:
      "[mail.smtp.auth]": false
      "[mail.smtp.starttls.enable]": false
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000


app:
  rabbit:
    queue: crm.campaign.queue
    exchange: crm.exchange
    routing-key: crm.campaign.created
    dlq: crm.campaigns.dlq
    dlx: crm.dlx

  report:
    email:
      from: no-reply@local.test
      to: admin@local.test
      subject: Campaign report
      smoke-test:
        enabled: true
    excel:
      smoke-test:
        enabled: true
    schedule: "0 */3 * * * *"

logging:
  level:
    org.springframework.amqp: DEBUG

server:
  port: 8081