spring:
  application:
    name: event-worker

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbit:
    queue: crm.campaign.queue

  datasource:
    url: jdbc:postgresql://localhost:5432/ess_data
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081