package com.spx.mappers;

import com.spx.dto.CampaignEventDTO;
import com.spx.models.Campaign;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/*
 * MapStruct mapper responsible for converting CampaignEventDTO objects into Campaign entities.
 * The mapper also relies on AttendeeMapper to convert nested AttendeeDTO objects into Attendee entities.
 */
@Mapper(componentModel = "spring", uses = AttendeeMapper.class)
public interface CampaignMapper {

    /*
     * Maps a CampaignEventDTO to a Campaign entity.
     * The "id" field is ignored because it is generated by the database (auto-generated primary key).
     * The attendees list will be automatically mapped (uses attribute).
     */
    @Mapping(target = "id", ignore = true)
    Campaign toEntity(CampaignEventDTO dto);

}