services:

  postgres:
    image: postgres:16
    container_name: ess-postgres
    environment:
      POSTGRES_DB: ess_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d ess_data"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ess-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:

      # Use `gosu` to run the RabbitMQ health check as the `rabbitmq` user.
      # Without it, Docker runs the health check command as `root`, and the check fails.
      test: ["CMD", "gosu", "rabbitmq", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5